[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-rust-os.json"  # Use this target when running `cargo build`.

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
